name: Deploy to Railway

defaults:
  run:
    working-directory: ./backend
    
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: npm install
        
      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test
